export const ACTION_TYPES = {
  LOAD_INITIAL_DATA: 'LOAD_INITIAL_DATA',
  CREATE_TICKET: 'CREATE_TICKET',
  ADD_REPLY: 'ADD_REPLY',
  ASSIGN_TICKET: 'ASSIGN_TICKET',
  UPDATE_TICKET_PRIORITY: 'UPDATE_TICKET_PRIORITY',
  UPDATE_TICKET_STATUS: 'UPDATE_TICKET_STATUS',
  SET_FILTERS: 'SET_FILTERS',
  SET_SEARCH: 'SET_SEARCH',
  SET_SORT: 'SET_SORT',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
}
